export const emojiNameMap: { [emoji: string]: string[] } = {
  "😀": ["grinning face", "smile"],
  "😁": ["beaming face", "smile", "grin"],
  "😂": ["face with tears of joy", "joy", "tears", "laugh"],
  "🤣": ["rolling on the floor laughing", "rofl", "laugh"],
  "😃": ["grinning face with big eyes", "smile", "happy"],
  "😄": ["grinning face with smiling eyes", "smile", "happy"],
  "😅": ["grinning face with sweat", "sweat", "awkward"],
  "😆": ["grinning squinting face", "laugh", "squint"],
  "😉": ["winking face", "wink"],
  "😊": ["smiling face with smiling eyes", "smile", "blush"],
  "😋": ["face savoring food", "yum", "delicious"],
  "😎": ["smiling face with sunglasses", "cool", "sunglasses"],
  "😍": ["smiling face with heart-eyes", "love", "heart eyes"],
  "😘": ["face blowing a kiss", "kiss", "love"],
  "🥰": ["smiling face with hearts", "hearts", "in love"],
  "😗": ["kissing face", "kiss"],
  "😙": ["kissing face with smiling eyes", "kiss", "smile"],
  "😚": ["kissing face with closed eyes", "kiss", "closed eyes"],
  "🙂": ["slightly smiling face", "smile"],
  "🤗": ["hugging face", "hug"],
  "🤩": ["star-struck", "star", "amazed"],
  "🤔": ["thinking face", "think", "hmm"],
  "🤨": ["face with raised eyebrow", "suspicious", "doubt"],
  "😐": ["neutral face", "neutral"],
  "😑": ["expressionless face", "expressionless"],
  "😶": ["face without mouth", "silent", "mute"],
  "🙄": ["face with rolling eyes", "eyeroll", "annoyed"],
  "😏": ["smirking face", "smirk"],
  "😒": ["unamused face", "unamused"],
  "😓": ["downcast face with sweat", "sweat", "downcast"],
  "😔": ["pensive face", "pensive", "sad"],
  "😕": ["confused face", "confused"],
  "🙃": ["upside-down face", "upside down", "silly"],
  "🤑": ["money-mouth face", "money", "rich"],
  "😲": ["astonished face", "astonished", "surprised"],
  "☹️": ["frowning face", "frown", "sad"],
  "🙁": ["slightly frowning face", "frown", "sad"],
  "😖": ["confounded face", "confounded", "frustrated"],
  "😞": ["disappointed face", "disappointed", "sad"],
  "😟": ["worried face", "worried", "concerned"],
  "😤": ["face with steam from nose", "steam", "angry", "triumph"],
  "😢": ["crying face", "cry", "sad", "tear"],
  "😭": ["loudly crying face", "cry", "sad", "tears"],
  "😦": ["frowning face with open mouth", "frown", "open mouth"],
  "😧": ["anguished face", "anguished", "upset"],
  "😨": ["fearful face", "fearful", "scared"],
  "😩": ["weary face", "weary", "tired"],
  "🤯": ["exploding head", "mind blown", "explosion"],
  "😬": ["grimacing face", "grimace", "awkward"],
  "😰": ["anxious face with sweat", "anxious", "sweat"],
  "😱": ["face screaming in fear", "scream", "fear"],
  "🥵": ["hot face", "hot", "overheated"],
  "🥶": ["cold face", "cold", "freezing"],
  "😳": ["flushed face", "flushed", "embarrassed"],
  "🤪": ["zany face", "zany", "crazy", "silly"],
  "😵": ["dizzy face", "dizzy", "confused"],
  "😡": ["pouting face", "pout", "angry"],
  "😠": ["angry face", "angry", "mad"],
  "🤬": ["face with symbols on mouth", "swearing", "cursing", "angry"],
  "😷": ["face with medical mask", "mask", "sick"],
  "🤒": ["face with thermometer", "thermometer", "sick"],
  "🤕": ["face with head-bandage", "bandage", "injured"],
  "🤢": ["nauseated face", "nauseated", "sick"],
  "🤮": ["face vomiting", "vomit", "sick"],
  "🤧": ["sneezing face", "sneeze", "sick"],
  "😇": ["smiling face with halo", "halo", "angel"],
  "🥳": ["partying face", "party", "celebrate"],
  "🥺": ["pleading face", "pleading", "begging"],
  "🤠": ["cowboy hat face", "cowboy", "hat"],
  "🤡": ["clown face", "clown"],
  "🤥": ["lying face", "lying", "lie"],
  "🤫": ["shushing face", "shush", "quiet"],
  "🤭": ["face with hand over mouth", "hand over mouth", "oops"],
  "🧐": ["face with monocle", "monocle", "inspector"],
  "🤓": ["nerd face", "nerd", "geek"],
  "😈": ["smiling face with horns", "devil", "horns"],
  "👿": ["angry face with horns", "angry", "devil", "horns"],
  "👹": ["ogre", "monster", "oni"],
  "👺": ["goblin", "tengu", "monster"],
  "💀": ["skull", "death", "dead"],
  "👻": ["ghost", "spooky", "boo"],
  "👽": ["alien", "ufo", "extraterrestrial"],
  "👾": ["alien monster", "monster", "game"],
  "🤖": ["robot", "robot face", "bot"],
  "😺": ["grinning cat", "cat", "smile"],
  "😸": ["grinning cat with smiling eyes", "cat", "smile"],
  "😹": ["cat with tears of joy", "cat", "joy", "tears"],
  "😻": ["smiling cat with heart-eyes", "cat", "love", "heart eyes"],
  "😼": ["cat with wry smile", "cat", "smirk"],
  "😽": ["kissing cat", "cat", "kiss"],
  "🙀": ["weary cat", "cat", "weary", "scared"],
  "😿": ["crying cat", "cat", "cry", "sad"],
  "😾": ["pouting cat", "cat", "angry"],
  "😥": ["sad but relieved face", "relieved", "sad"],
  "🤤": ["drooling face", "drool", "hungry"],
  "😴": ["sleeping face", "sleep", "tired"],
  "😪": ["sleepy face", "sleepy", "tired"],
  "🥱": ["yawning face", "yawn", "tired"],
  "☠️": ["skull and crossbones", "danger", "death"],
  "🎃": ["jack-o-lantern", "halloween", "pumpkin"],
  "🙈": ["see-no-evil monkey", "monkey", "see no evil"],
  "💩": ["pile of poo", "poop", "shit", "smile"],
  "🔥": ["fire", "lit", "hot"],
  "✨": ["sparkles", "stars", "shine"],
  "🌟": ["glowing star", "star", "glow"],
  "💫": ["dizzy", "sparkle", "dizzy"],
  "💥": ["collision", "boom", "explosion"],
  "💦": ["sweat droplets", "sweat", "water"],
  "💨": ["dashing away", "wind", "dash"],
  "🕳️": ["hole", "pit", "hole"],
  "💣": ["bomb", "explosion", "boom"],
  "💬": ["speech balloon", "chat", "talk"],
  "👋": ["waving hand", "wave", "hello"],
  "🤚": ["raised back of hand", "hand", "backhand"],
  "🖐️": ["hand with fingers splayed", "hand", "fingers"],
  "✋": ["raised hand", "hand", "stop"],
  "🖖": ["vulcan salute", "spock", "salute"],
  "👌": ["ok hand", "ok", "perfect"],
  "🤌": ["pinched fingers", "italian", "fingers"],
  "🤏": ["pinching hand", "pinch", "small"],
  "✌️": ["victory hand", "peace", "victory"],
  "🤞": ["crossed fingers", "luck", "fingers crossed"],
  "🤟": ["love-you gesture", "love you", "rock on"],
  "🤘": ["sign of the horns", "rock", "horns"],
  "🤙": ["call me hand", "call me", "shaka"],
  "👈": ["backhand index pointing left", "left", "point"],
  "👉": ["backhand index pointing right", "right", "point"],
  "👆": ["backhand index pointing up", "up", "point"],
  "🖕": ["middle finger", "rude", "middle"],
  "👇": ["backhand index pointing down", "down", "point"],
  "☝️": ["index pointing up", "up", "point"],
  "👍": ["thumbs up", "like", "approve"],
  "👎": ["thumbs down", "dislike", "disapprove"],
  "✊": ["raised fist", "fist", "power"],
  "👊": ["oncoming fist", "fist bump", "punch"],
  "🤛": ["left-facing fist", "fist", "left"],
  "🤜": ["right-facing fist", "fist", "right"],
  "👏": ["clapping hands", "clap", "applause"],
  "🙌": ["raising hands", "hooray", "celebrate"],
  "👐": ["open hands", "hug", "open"],
  "🤲": ["palms up together", "beg", "please"],
  "🙏": ["folded hands", "pray", "thanks"],
  "✍️": ["writing hand", "write", "writing"],
  "💅": ["nail polish", "nails", "manicure"],
  "🤳": ["selfie", "selfie hand", "photo"],
  "💪": ["flexed biceps", "strong", "muscle"],
  "🦾": ["mechanical arm", "robot arm", "strong"],
  "🦵": ["leg", "kick", "leg"],
  "🦶": ["foot", "walk", "foot"],
  "👂": ["ear", "listen", "hear"],
  "🦻": ["ear with hearing aid", "hearing aid", "ear"],
  "👃": ["nose", "smell", "nose"],
  "🧠": ["brain", "think", "mind"],
  "🦷": ["tooth", "teeth", "tooth"],
  "🦴": ["bone", "skeleton", "bone"],
  "👀": ["eyes", "look", "see"],
  "👁️": ["eye", "look", "see"],
  "👅": ["tongue", "taste", "tongue"],
  "👄": ["mouth", "talk", "mouth"],
  "🧑‍🦰": ["person: red hair", "red hair", "person"],
  "🧑‍🦱": ["person: curly hair", "curly hair", "person"],
  "🧑‍🦳": ["person: white hair", "white hair", "person"],
  "🧑‍🦲": ["person: bald", "bald", "person"],
  "👶": ["baby", "infant", "child"],
  "🧒": ["child", "kid", "young"],
  "👦": ["boy", "male child", "boy"],
  "👧": ["girl", "female child", "girl"],
  "🧑": ["person", "adult", "human"],
  "👱": ["person: blond hair", "blond", "person"],
  "👨": ["man", "male", "man"],
  "👩": ["woman", "female", "woman"],
  "🧔": ["person: beard", "beard", "person"],
  "👴": ["old man", "elder", "man"],
  "👵": ["old woman", "elder", "woman"],
  "🧓": ["older person", "elder", "person"],
  "👲": ["person with skullcap", "skullcap", "person"],
  "👳": ["person with turban", "turban", "person"],
  "🧕": ["woman with headscarf", "headscarf", "woman"],
  "👮": ["police officer", "police", "officer"],
  "🕵️": ["detective", "spy", "detective"],
  "💂": ["guard", "british guard", "guard"],
  "👷": ["construction worker", "worker", "builder"],
  "🦸": ["superhero", "hero", "super"],
  "🦹": ["supervillain", "villain", "super"],
  "🧙": ["mage", "wizard", "magic"],
  "🧚": ["fairy", "magic", "fairy"],
  "🧛": ["vampire", "vampire", "monster"],
  "🧜": ["merperson", "mermaid", "merman"],
  "🧝": ["elf", "fantasy", "elf"],
  "🧞": ["genie", "magic", "genie"],
  "🧟": ["zombie", "undead", "zombie"],
  "🦸‍♂️": ["man superhero", "superhero", "man"],
  "🦸‍♀️": ["woman superhero", "superhero", "woman"],
  "🦹‍♂️": ["man supervillain", "supervillain", "man"],
  "🦹‍♀️": ["woman supervillain", "supervillain", "woman"],
  "👸": ["princess", "royal", "princess"],
  "🤴": ["prince", "royal", "prince"],
  "👰": ["bride", "wedding", "bride"],
  "🤵": ["groom", "wedding", "groom"],
  "🤰": ["pregnant woman", "pregnant", "woman"],
  "🤱": ["breast-feeding", "baby", "feed"],
  "👼": ["baby angel", "angel", "baby"],
  "🎅": ["santa claus", "santa", "christmas"],
  "🤶": ["mrs. claus", "mrs claus", "christmas"],
  "🧑‍🎄": ["mx claus", "christmas", "claus"],
  "🦄": ["unicorn", "fantasy", "magic"],
  "🐶": ["dog", "puppy", "pet"],
  "🐱": ["cat", "kitty", "pet"],
  "🐭": ["mouse", "rodent", "cute"],
  "🐹": ["hamster", "rodent", "cute"],
  "🐰": ["rabbit", "bunny", "cute"],
  "🦊": ["fox", "fox face", "sly"],
  "🐻": ["bear", "bear face", "grizzly"],
  "🐼": ["panda", "panda face", "bear"],
  "🐨": ["koala", "koala face", "bear"],
  "🐯": ["tiger", "tiger face", "cat"],
  "🦁": ["lion", "lion face", "king"],
  "🐮": ["cow", "cow face", "moo"],
  "🐷": ["pig", "pig face", "oink"],
  "🐸": ["frog", "frog face", "ribbit"],
  "🐵": ["monkey", "monkey face", "primate"],
  "🙉": ["hear-no-evil monkey", "monkey", "hear no evil"],
  "🙊": ["speak-no-evil monkey", "monkey", "speak no evil"],
  "🦋": ["butterfly", "insect", "fly"],
  "🐞": ["lady beetle", "ladybug", "insect"],
  "🐢": ["turtle", "reptile", "slow"],
  "🐍": ["snake", "serpent", "reptile"],
  "🦖": ["t-rex", "dinosaur", "trex"],
  "🦕": ["sauropod", "dinosaur", "brontosaurus"],
  "🦀": ["crab", "seafood", "crustacean"],
  "🦑": ["squid", "seafood", "octopus"],
  "🐙": ["octopus", "sea", "tentacle"],
  "🦞": ["lobster", "seafood", "crustacean"],
  "🦐": ["shrimp", "seafood", "crustacean"],
  "🦦": ["otter", "animal", "cute"],
  "🦥": ["sloth", "animal", "slow"],
  "🦨": ["skunk", "animal", "smelly"],
  "🦘": ["kangaroo", "animal", "australia"],
  "🦡": ["badger", "animal", "dig"],
  "🦔": ["hedgehog", "animal", "spiky"],
  "🦇": ["bat", "animal", "night"],
  "🦅": ["eagle", "bird", "freedom"],
  "🦉": ["owl", "bird", "wise"],
  "🦆": ["duck", "bird", "quack"],
  "🦤": ["dodo", "bird", "extinct"],
  "🦭": ["seal", "animal", "sea"],
  "🐧": ["penguin", "bird", "cold"],
  "🐦": ["bird", "tweet", "fly"],
  "🐤": ["chick", "bird", "baby"],
  "🐣": ["hatching chick", "bird", "baby"],
  "🐥": ["front-facing chick", "bird", "baby"],
  "🦢": ["swan", "bird", "grace"],
  "🦩": ["flamingo", "bird", "pink"],
  "🦚": ["peacock", "bird", "colorful"],
  "🦜": ["parrot", "bird", "talk"],
  "🦓": ["zebra", "animal", "stripe"],
  "🦒": ["giraffe", "animal", "tall"],
  "🦛": ["hippopotamus", "animal", "hippo"],
  "🦏": ["rhinoceros", "animal", "rhino"],
  "🐪": ["camel", "animal", "desert"],
  "🐫": ["two-hump camel", "animal", "desert"],
  "🦬": ["bison", "animal", "buffalo"],
  "🐘": ["elephant", "animal", "trunk"],
  "🦣": ["mammoth", "animal", "extinct"],
  "🐐": ["goat", "animal", "bleat"],
  "🐏": ["ram", "animal", "sheep"],
  "🐑": ["sheep", "animal", "wool"],
  "🐎": ["horse", "animal", "ride"],
  "🦙": ["llama", "animal", "spit"],
  "🦌": ["deer", "animal", "antler"],
  "🦃": ["turkey", "bird", "thanksgiving"],
  "🐓": ["rooster", "bird", "chicken"],
  "🦫": ["beaver", "animal", "dam"],
  "🐉": ["dragon", "mythical", "fantasy"],
  "🐲": ["dragon face", "mythical", "fantasy"],
  "🦎": ["lizard", "reptile", "animal"],
  "🐊": ["crocodile", "reptile", "animal"],
  "🐬": ["dolphin", "animal", "sea"],
  "🐳": ["spouting whale", "animal", "sea"],
  "🐋": ["whale", "animal", "sea"],
  "🦈": ["shark", "animal", "sea"],
  "🐅": ["tiger", "animal", "cat"],
  "🐆": ["leopard", "animal", "cat"],
  "🍏": ["green apple", "apple", "fruit"],
  "🍎": ["red apple", "apple", "fruit"],
  "🍐": ["pear", "fruit"],
  "🍊": ["tangerine", "orange", "fruit"],
  "🍋": ["lemon", "fruit"],
  "🍌": ["banana", "fruit"],
  "🍉": ["watermelon", "fruit"],
  "🍇": ["grapes", "fruit"],
  "🍓": ["strawberry", "fruit"],
  "🫐": ["blueberries", "fruit"],
  "🍈": ["melon", "fruit"],
  "🍒": ["cherries", "fruit"],
  "🍑": ["peach", "fruit"],
  "🥭": ["mango", "fruit"],
  "🍍": ["pineapple", "fruit"],
  "🥥": ["coconut", "fruit"],
  "🥝": ["kiwi", "fruit"],
  "🍅": ["tomato", "fruit", "vegetable"],
  "🍆": ["eggplant", "vegetable"],
  "🥑": ["avocado", "fruit"],
  "🥦": ["broccoli", "vegetable"],
  "🥬": ["leafy green", "vegetable"],
  "🥒": ["cucumber", "vegetable"],
  "🌶️": ["hot pepper", "chili", "vegetable"],
  "🌽": ["corn", "vegetable"],
  "🥕": ["carrot", "vegetable"],
  "🧄": ["garlic", "vegetable"],
  "🧅": ["onion", "vegetable"],
  "🥔": ["potato", "vegetable"],
  "🍠": ["roasted sweet potato", "sweet potato", "vegetable"],
  "🥐": ["croissant", "bread", "pastry"],
  "🥯": ["bagel", "bread"],
  "🍞": ["bread", "loaf"],
  "🥖": ["baguette bread", "bread"],
  "🥨": ["pretzel", "bread", "snack"],
  "🥞": ["pancakes", "breakfast", "food"],
  "🧇": ["waffle", "breakfast", "food"],
  "🧀": ["cheese", "food"],
  "🍖": ["meat on bone", "meat", "food"],
  "🍗": ["poultry leg", "chicken", "food"],
  "🥩": ["cut of meat", "steak", "food"],
  "🥓": ["bacon", "food"],
  "🍔": ["hamburger", "burger", "food"],
  "🍟": ["french fries", "fries", "food"],
  "🍕": ["pizza", "food"],
  "🌭": ["hot dog", "food"],
  "🥪": ["sandwich", "food"],
  "🌮": ["taco", "food"],
  "🌯": ["burrito", "food"],
  "🫔": ["tamale", "food"],
  "🥙": ["stuffed flatbread", "food"],
  "🧆": ["falafel", "food"],
  "🥚": ["egg", "food"],
  "🍳": ["cooking", "fried egg", "food"],
  "🥘": ["shallow pan of food", "paella", "food"],
  "🍲": ["pot of food", "stew", "food"],
  "🥣": ["bowl with spoon", "breakfast", "food"],
  "🥗": ["green salad", "salad", "food"],
  "🍿": ["popcorn", "snack", "food"],
  "🧈": ["butter", "food"],
  "🧂": ["salt", "seasoning", "food"],
  "🥫": ["canned food", "food"],
  "🍱": ["bento box", "food"],
  "🍘": ["rice cracker", "food"],
  "🍙": ["rice ball", "food"],
  "🍚": ["cooked rice", "food"],
  "🍛": ["curry rice", "food"],
  "🍜": ["steaming bowl", "ramen", "noodles", "food"],
  "🍝": ["spaghetti", "pasta", "food"],
  "🍢": ["oden", "food"],
  "🍣": ["sushi", "food"],
  "🍤": ["fried shrimp", "food"],
  "🍥": ["fish cake with swirl", "food"],
  "🥮": ["moon cake", "food"],
  "🍡": ["dango", "food"],
  "🥟": ["dumpling", "food"],
  "🥠": ["fortune cookie", "food"],
  "🥡": ["takeout box", "food"],
  "🦪": ["oyster", "food"],
  "🍦": ["soft ice cream", "dessert", "food"],
  "🍧": ["shaved ice", "dessert", "food"],
  "🍨": ["ice cream", "dessert", "food"],
  "🍩": ["doughnut", "dessert", "food"],
  "🍪": ["cookie", "dessert", "food"],
  "🎂": ["birthday cake", "cake", "dessert"],
  "🍰": ["shortcake", "cake", "dessert"],
  "🧁": ["cupcake", "dessert", "food"],
  "🥧": ["pie", "dessert", "food"],
  "🍫": ["chocolate bar", "dessert", "food"],
  "🍬": ["candy", "dessert", "food"],
  "🍭": ["lollipop", "dessert", "food"],
  "🍮": ["custard", "dessert", "food"],
  "🍯": ["honey pot", "honey", "food"],
  "🍼": ["baby bottle", "drink", "milk"],
  "🥛": ["glass of milk", "drink", "milk"],
  "☕": ["hot beverage", "coffee", "tea", "drink"],
  "🫖": ["teapot", "tea", "drink"],
  "🍵": ["teacup without handle", "tea", "drink"],
  "🍶": ["sake", "drink", "alcohol"],
  "🍾": ["bottle with popping cork", "champagne", "drink", "alcohol"],
  "🍷": ["wine glass", "drink", "alcohol"],
  "🍸": ["cocktail glass", "drink", "alcohol"],
  "🍹": ["tropical drink", "drink", "alcohol"],
  "🍺": ["beer mug", "drink", "alcohol"],
  "🍻": ["clinking beer mugs", "drink", "alcohol"],
  "🥂": ["clinking glasses", "drink", "alcohol"],
  "🥃": ["tumbler glass", "drink", "alcohol"],
  "🫗": ["pouring liquid", "drink"],
  "🥤": ["cup with straw", "drink", "soda"],
  "🧋": ["bubble tea", "drink", "boba"],
  "🧃": ["beverage box", "drink", "juice"],
  "🧉": ["mate", "drink"],
  "🧊": ["ice", "drink"],
  "☀️": ["sun", "sunny", "weather"],
  "🌤️": ["sun behind small cloud", "partly sunny", "weather"],
  "⛅": ["sun behind cloud", "partly cloudy", "weather"],
  "🌥️": ["sun behind large cloud", "cloudy", "weather"],
  "☁️": ["cloud", "weather"],
  "🌦️": ["sun behind rain cloud", "showers", "weather"],
  "🌧️": ["cloud with rain", "rain", "weather"],
  "⛈️": ["cloud with lightning and rain", "thunderstorm", "weather"],
  "🌩️": ["cloud with lightning", "lightning", "weather"],
  "🌨️": ["cloud with snow", "snow", "weather"],
  "❄️": ["snowflake", "snow", "weather"],
  "☃️": ["snowman", "snow", "weather"],
  "⛄": ["snowman without snow", "snow", "weather"],
  "🌬️": ["wind face", "wind", "weather"],
  "🌪️": ["tornado", "twister", "weather"],
  "🌫️": ["fog", "weather"],
  "🌈": ["rainbow", "weather", "nature"],
  "🌂": ["closed umbrella", "umbrella", "weather"],
  "☔": ["umbrella with rain drops", "umbrella", "weather"],
  "🌊": ["water wave", "ocean", "nature"],
  "🌋": ["volcano", "nature", "eruption"],
  "🪨": ["rock", "nature", "stone"],
  "🪵": ["wood", "log", "nature"],
  "🌳": ["deciduous tree", "tree", "nature"],
  "🌲": ["evergreen tree", "tree", "nature"],
  "🌴": ["palm tree", "tree", "nature"],
  "🌵": ["cactus", "plant", "nature"],
  "🌾": ["sheaf of rice", "plant", "nature"],
  "🌿": ["herb", "plant", "nature"],
  "☘️": ["shamrock", "clover", "nature"],
  "🍀": ["four leaf clover", "clover", "nature"],
  "🍁": ["maple leaf", "leaf", "nature"],
  "🍂": ["fallen leaf", "leaf", "nature"],
  "🍃": ["leaf fluttering in wind", "leaf", "nature"],
  "🍽️": ["fork and knife with plate", "silverware", "plate"],
  "🍴": ["fork and knife", "silverware"],
  "🥄": ["spoon", "silverware"],
  "🔪": ["kitchen knife", "knife", "silverware"],
  "🥢": ["chopsticks", "silverware"],
  "⚽": ["soccer ball", "football", "sport", "activity"],
  "🏀": ["basketball", "sport", "activity"],
  "🏈": ["american football", "sport", "activity"],
  "⚾": ["baseball", "sport", "activity"],
  "🥎": ["softball", "sport", "activity"],
  "🎾": ["tennis", "sport", "activity"],
  "🏐": ["volleyball", "sport", "activity"],
  "🏉": ["rugby football", "sport", "activity"],
  "🎱": ["pool 8 ball", "billiards", "activity"],
  "🏓": ["ping pong", "table tennis", "activity"],
  "🏸": ["badminton", "activity"],
  "🥅": ["goal net", "sport", "activity"],
  "🏒": ["ice hockey", "sport", "activity"],
  "🏑": ["field hockey", "sport", "activity"],
  "🏏": ["cricket", "sport", "activity"],
  "🥍": ["lacrosse", "sport", "activity"],
  "🏹": ["bow and arrow", "archery", "activity"],
  "🎣": ["fishing pole", "fishing", "activity"],
  "🤿": ["diving mask", "snorkeling", "activity"],
  "🥊": ["boxing glove", "boxing", "activity"],
  "🥋": ["martial arts uniform", "karate", "activity"],
  "🎽": ["running shirt", "sport", "activity"],
  "🛹": ["skateboard", "activity"],
  "🛼": ["roller skate", "activity"],
  "🛷": ["sled", "activity"],
  "⛸️": ["ice skate", "activity"],
  "🥌": ["curling stone", "activity"],
  "🎿": ["skis", "skiing", "activity"],
  "⛷️": ["skier", "skiing", "activity"],
  "🏂": ["snowboarder", "snowboarding", "activity"],
  "🏋️": ["person lifting weights", "weightlifting", "activity"],
  "🤼": ["people wrestling", "wrestling", "activity"],
  "🤸": ["person cartwheeling", "gymnastics", "activity"],
  "⛹️": ["person bouncing ball", "basketball", "activity"],
  "🤺": ["person fencing", "fencing", "activity"],
  "🤾": ["person playing handball", "handball", "activity"],
  "🏌️": ["person golfing", "golf", "activity"],
  "🏇": ["horse racing", "activity"],
  "🧘": ["person in lotus position", "yoga", "activity"],
  "🏄": ["person surfing", "surfing", "activity"],
  "🏊": ["person swimming", "swimming", "activity"],
  "🤽": ["person playing water polo", "water polo", "activity"],
  "🚣": ["person rowing boat", "rowing", "activity"],
  "🧗": ["person climbing", "climbing", "activity"],
  "🚴": ["person biking", "biking", "activity"],
  "🚵": ["person mountain biking", "mountain biking", "activity"],
  "🤹": ["person juggling", "juggling", "activity"],
  "🎤": ["microphone", "singing", "music", "activity"],
  "🎧": ["headphone", "music", "activity"],
  "🎼": ["musical score", "music", "activity"],
  "🎹": ["musical keyboard", "piano", "music", "activity"],
  "🥁": ["drum", "music", "activity"],
  "🎷": ["saxophone", "music", "activity"],
  "🎺": ["trumpet", "music", "activity"],
  "🎸": ["guitar", "music", "activity"],
  "🪕": ["banjo", "music", "activity"],
  "🎻": ["violin", "music", "activity"],
  "🎬": ["clapper board", "movie", "film", "activity"],
  "🎮": ["video game", "gaming", "activity"],
  "🕹️": ["joystick", "gaming", "activity"],
  "🎲": ["game die", "dice", "activity"],
  "🧩": ["puzzle piece", "activity"],
  "♟️": ["chess pawn", "chess", "activity"],
  "🚗": ["car", "automobile", "vehicle"],
  "🚕": ["taxi", "cab", "vehicle"],
  "🚙": ["sport utility vehicle", "suv", "vehicle"],
  "🛻": ["pickup truck", "truck", "vehicle"],
  "🚚": ["delivery truck", "truck", "vehicle"],
  "🚛": ["articulated lorry", "semi truck", "vehicle"],
  "🚜": ["tractor", "farm vehicle", "vehicle"],
  "🏎️": ["racing car", "racecar", "vehicle"],
  "🏍️": ["motorcycle", "bike", "vehicle"],
  "🛵": ["motor scooter", "scooter", "vehicle"],
  "🦽": ["manual wheelchair", "wheelchair", "mobility"],
  "🦼": ["motorized wheelchair", "powered wheelchair", "mobility"],
  "🛴": ["kick scooter", "scooter", "vehicle"],
  "🚲": ["bicycle", "bike", "cycle", "vehicle"],
  "🛺": ["auto rickshaw", "tuk tuk", "vehicle"],
  "🚨": ["police car light", "siren", "emergency"],
  "🚓": ["police car", "cop car", "vehicle"],
  "🚑": ["ambulance", "emergency", "vehicle"],
  "🚒": ["fire engine", "fire truck", "vehicle"],
  "🚐": ["minibus", "van", "vehicle"],
  "🚍": ["bus", "vehicle"],
  "🚌": ["bus", "vehicle"],
  "🚎": ["trolleybus", "vehicle"],
  "🚏": ["bus stop", "public transport"],
  "🚃": ["railway car", "train", "vehicle"],
  "🚋": ["tram car", "vehicle"],
  "🚞": ["mountain railway", "train", "vehicle"],
  "🚝": ["monorail", "train", "vehicle"],
  "🚄": ["high-speed train", "shinkansen", "vehicle"],
  "🚅": ["bullet train", "shinkansen", "vehicle"],
  "🚈": ["light rail", "train", "vehicle"],
  "🚂": ["locomotive", "train", "vehicle"],
  "🚆": ["train", "vehicle"],
  "🚇": ["metro", "subway", "underground", "vehicle"],
  "🚊": ["tram", "streetcar", "vehicle"],
  "🚉": ["station", "train station", "public transport"],
  "🚁": ["helicopter", "aircraft", "vehicle"],
  "🛩️": ["small airplane", "aircraft", "vehicle"],
  "✈️": ["airplane", "plane", "aircraft", "vehicle"],
  "🛫": ["airplane departure", "takeoff", "vehicle"],
  "🛬": ["airplane arrival", "landing", "vehicle"],
  "🛳️": ["passenger ship", "cruise", "boat", "vehicle"],
  "⛴️": ["ferry", "boat", "vehicle"],
  "🚢": ["ship", "boat", "vehicle"],
  "⛵": ["sailboat", "boat", "vehicle"],
  "🛥️": ["motor boat", "boat", "vehicle"],
  "🚤": ["speedboat", "boat", "vehicle"],
  "🛶": ["canoe", "boat", "vehicle"],
  "🚟": ["suspension railway", "vehicle"],
  "🚠": ["mountain cableway", "vehicle"],
  "🚡": ["aerial tramway", "vehicle"],
  "🦯": ["white cane", "blind", "mobility"],
  "🩼": ["crutch", "crutches", "mobility aid"],
  "🛂": ["passport control", "travel"],
  "🛃": ["customs", "travel"],
  "🛄": ["baggage claim", "luggage", "travel"],
  "🛅": ["left luggage", "luggage", "travel"],
  "❤️": ["red heart", "love", "heart"],
  "🧡": ["orange heart", "heart"],
  "💛": ["yellow heart", "heart"],
  "💚": ["green heart", "heart"],
  "💙": ["blue heart", "heart"],
  "💜": ["purple heart", "heart"],
  "🖤": ["black heart", "heart"],
  "🤍": ["white heart", "heart"],
  "🤎": ["brown heart", "heart"],
  "💔": ["broken heart", "heart", "sad"],
  "❣️": ["heart exclamation", "love", "heart"],
  "💕": ["two hearts", "love", "heart"],
  "💞": ["revolving hearts", "love", "heart"],
  "💓": ["beating heart", "love", "heart"],
  "💗": ["growing heart", "love", "heart"],
  "💖": ["sparkling heart", "love", "heart"],
  "💘": ["heart with arrow", "love", "heart"],
  "💝": ["heart with ribbon", "love", "heart"],
  "💟": ["heart decoration", "love", "heart"],
  "♈": ["aries", "zodiac"],
  "♉": ["taurus", "zodiac"],
  "♊": ["gemini", "zodiac"],
  "♋": ["cancer", "zodiac"],
  "♌": ["leo", "zodiac"],
  "♍": ["virgo", "zodiac"],
  "♎": ["libra", "zodiac"],
  "♏": ["scorpio", "zodiac"],
  "♐": ["sagittarius", "zodiac"],
  "♑": ["capricorn", "zodiac"],
  "♒": ["aquarius", "zodiac"],
  "♓": ["pisces", "zodiac"],
  "⛎": ["ophiuchus", "zodiac"],
  "⚠️": ["warning", "alert", "caution"],
  "🚸": ["children crossing", "warning", "sign"],
  "⛔": ["no entry", "prohibited", "sign"],
  "🚫": ["prohibited", "no", "sign"],
  "🚷": ["no pedestrians", "prohibited", "sign"],
  "🚯": ["no littering", "prohibited", "sign"],
  "🚳": ["no bicycles", "prohibited", "sign"],
  "🚱": ["non-potable water", "warning", "sign"],
  "🔞": ["18 prohibited", "adult", "warning"],
  "☢️": ["radioactive", "warning", "sign"],
  "☣️": ["biohazard", "warning", "sign"],
  "♻️": ["recycling symbol", "recycle", "eco"],
  "🔆": ["bright button", "brightness", "symbol"],
  "🔅": ["dim button", "brightness", "symbol"],
  "🔱": ["trident emblem", "trident", "symbol"],
  "⚜️": ["fleur-de-lis", "symbol"],
  "🔯": ["six pointed star with dot", "star", "symbol"],
  "✡️": ["star of david", "jewish", "symbol"],
  "☸️": ["wheel of dharma", "buddhist", "symbol"],
  "☯️": ["yin yang", "tao", "symbol"],
  "✝️": ["latin cross", "christian", "symbol"],
  "☦️": ["orthodox cross", "christian", "symbol"],
  "☪️": ["star and crescent", "islam", "symbol"],
  "☮️": ["peace symbol", "peace", "symbol"],
  "🕉️": ["om", "hindu", "symbol"],
  "🔔": ["bell", "notification", "symbol"],
  "🔕": ["bell with slash", "mute", "notification"],
  "⬆️": ["up arrow", "arrow", "direction"],
  "⬇️": ["down arrow", "arrow", "direction"],
  "⬅️": ["left arrow", "arrow", "direction"],
  "➡️": ["right arrow", "arrow", "direction"],
  "↗️": ["up-right arrow", "arrow", "direction"],
  "↘️": ["down-right arrow", "arrow", "direction"],
  "↙️": ["down-left arrow", "arrow", "direction"],
  "↖️": ["up-left arrow", "arrow", "direction"],
  "↔️": ["left-right arrow", "arrow", "direction"],
  "↕️": ["up-down arrow", "arrow", "direction"],
  "⚓": ["anchor", "symbol"],
  "✂️": ["scissors", "cut", "symbol"],
  "✒️": ["black nib", "pen", "symbol"],
  "✏️": ["pencil", "edit", "symbol"],
  "✉️": ["envelope", "mail", "symbol"],
  "✳️": ["eight spoked asterisk", "asterisk", "symbol"],
  "✴️": ["eight pointed star", "star", "symbol"],
  "❇️": ["sparkle", "star", "symbol"],
  "❌": ["cross mark", "x", "symbol"],
  "⭕": ["hollow red circle", "circle", "symbol"],
  "➕": ["plus", "add", "symbol"],
  "➖": ["minus", "subtract", "symbol"],
  "➗": ["divide", "division", "symbol"],
  "➰": ["curly loop", "symbol"],
  "➿": ["double curly loop", "symbol"],
  "〽️": ["part alternation mark", "symbol"],
  "©️": ["copyright", "symbol"],
  "®️": ["registered", "symbol"],
  "™️": ["trademark", "symbol"],
  "🏳️‍🌈": ["rainbow flag", "pride", "lgbt", "flag"],
  "🏳️": ["white flag", "flag"],
  "🏴": ["black flag", "flag"],
  "🏁": ["chequered flag", "race", "finish", "flag"],
  "🚩": ["triangular flag", "flag"],
  "🏴‍☠️": ["pirate flag", "jolly roger", "flag"],
  "🖨️": ["printer", "office", "print"],
  "🖱️": ["computer mouse", "mouse", "office"],
  "🖲️": ["trackball", "office", "computer"],
  "🖋️": ["fountain pen", "pen", "office"],
  "🖊️": ["pen", "office", "write"],
  "🖌️": ["paintbrush", "art", "office"],
  "🖍️": ["crayon", "art", "office"],
  "📎": ["paperclip", "office", "stationery"],
  "🖇️": ["linked paperclips", "office", "stationery"],
  "📐": ["triangular ruler", "ruler", "office"],
  "📏": ["straight ruler", "ruler", "office"],
  "📌": ["pushpin", "office", "stationery"],
  "📍": ["round pushpin", "office", "stationery"],
  "📅": ["calendar", "date", "office"],
  "📆": ["tear-off calendar", "date", "office"],
  "📇": ["card index", "office"],
  "📋": ["clipboard", "office"],
  "📁": ["file folder", "office"],
  "📂": ["open file folder", "office"],
  "🗂️": ["card index dividers", "office"],
  "🗃️": ["card file box", "office"],
  "🗄️": ["file cabinet", "office"],
  "🗑️": ["wastebasket", "trash", "office"],
  "📧": ["e-mail", "email", "mail"],
  "📨": ["incoming envelope", "mail"],
  "📩": ["envelope with arrow", "mail"],
  "📤": ["outbox tray", "mail", "office"],
  "📥": ["inbox tray", "mail", "office"],
  "📦": ["package", "box", "mail"],
  "📫": ["closed mailbox with raised flag", "mailbox", "mail"],
  "📪": ["closed mailbox with lowered flag", "mailbox", "mail"],
  "📬": ["open mailbox with raised flag", "mailbox", "mail"],
  "📭": ["open mailbox with lowered flag", "mailbox", "mail"],
  "📃": ["page with curl", "paper", "document"],
  "📄": ["page facing up", "paper", "document"],
  "📰": ["newspaper", "news", "paper"],
  "🗞️": ["rolled-up newspaper", "news", "paper"],
  "🛏️": ["bed", "sleep", "furniture"],
  "🛋️": ["couch and lamp", "sofa", "furniture"],
  "🪑": ["chair", "furniture", "seat"],
  "🪟": ["window", "furniture"],
  "🪞": ["mirror", "furniture"],
  "🪠": ["plunger", "cleaning", "bathroom"],
  "🚽": ["toilet", "bathroom"],
  "🚿": ["shower", "bathroom"],
  "🛁": ["bathtub", "bathroom"],
  "🧸": ["teddy bear", "toy", "cute"],
  "🪀": ["yo-yo", "toy"],
  "🪁": ["kite", "toy", "outdoor"],
  "🪆": ["nesting dolls", "toy", "russian"],
  "📱": ["mobile phone", "cell phone", "electronics"],
  "📲": ["mobile phone with arrow", "cell phone", "electronics"],
  "☎️": ["telephone", "phone", "electronics"],
  "📞": ["telephone receiver", "phone", "electronics"],
  "📟": ["pager", "electronics"],
  "📠": ["fax machine", "electronics"],
  "💻": ["laptop", "computer", "electronics"],
  "🖥️": ["desktop computer", "computer", "electronics"],
};